version: '3.8'
services:
  db:
    image: postgres:16
    container_name: auth-db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U authuser -d authdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: krowty999
    ports:
      - "5433:5432"
    volumes:
      - ./habr-auth-go/migrations/init_scripts:/docker-entrypoint-initdb.d
      - auth-db-data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
#    volumes:
#      - ./redisdata:/data
    command: [ "redis-server", "--requirepass", "pass23j4j32j", "--appendonly", "yes", "--appendfsync", "everysec" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "pass23j4j32j", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  auth-service:
    restart: always
    build:
      context: ./habr-auth-go
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: authuser
      DB_PASSWORD: krowty999
      DB_NAME: authdb
      DB_PORT: 5432
      REDIS_PASSWORD: pass23j4j32j
      REDIS_ADDR: redis:6379
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka2:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka3:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    entrypoint: [ "sh", "-c", "sleep 20 && kafka-topics --create --topic my-topic --partitions 1 --replication-factor 3 --if-not-exists --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092" ]


volumes:
  auth-db-data:

